# ============================================================
# 07_interactive_visualization.R
# Interactive plots generated by R.
#
# IMPORTANT:
# This script creates a self-contained HTML artifact at runtime.
# No HTML source file is stored in the repository.
# ============================================================

library(tidyverse)
library(plotly)

dat <- read_csv("data/processed/millet_clean.csv", show_col_types=FALSE)

p <- ggplot(
  dat,
  aes(
    x=target_ec,
    y=total_dry_biomass_g,
    text=paste0(
      "Treatment: ", treatment,
      "<br>Replication: ", replication,
      "<br>EC: ", target_ec, " dS m⁻¹",
      "<br>Total dry biomass: ",
      round(total_dry_biomass_g, 2), " g"
    )
  )
) +
  geom_point(size=3) +
  geom_smooth(method="lm", se=FALSE) +
  labs(
    title="Interactive salinity–biomass relationship",
    x="Target salinity (dS m⁻¹)",
    y="Total dry biomass (g)"
  ) +
  theme_minimal()

interactive_plot <- ggplotly(p, tooltip="text")

# Runtime-only artifact:
htmlwidgets::saveWidget(
  interactive_plot,
  "millet_salt_tolerance_interactive.html",
  selfcontained=TRUE
)

message(
  "Interactive visualization created as a runtime artifact. ",
  "It is not included in the Git repository structure."
)
